name: crm_app
description: ETA Tenis Akademisi CRM uygulamasi
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.20.2
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/eta_logo.png
